# Generated by Django 6.0 on 2025-12-23 07:50

import VJISS_APP.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_User',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255, validators=[VJISS_APP.models.validator_password_length])),
                ('confirm_password', models.CharField(max_length=255, validators=[VJISS_APP.models.validator_password_length])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Male', max_length=6)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
