# Generated by Django 6.0 on 2025-12-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VJISS_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus_model',
            old_name='Module',
            new_name='module',
        ),
    ]
