# Generated by Django 6.0 on 2025-12-25 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VJISS_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_Model',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_log', models.ImageField(upload_to='course_logos/')),
                ('course_duration', models.CharField(max_length=50)),
                ('course_description', models.TextField()),
                ('course_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
            ],
        ),
    ]
