# Generated by Django 6.0 on 2025-12-26 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VJISS_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus_model',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Module', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_courses', to='VJISS_APP.courses_model')),
            ],
        ),
    ]
