# Generated by Django 6.0 on 2025-12-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VJISS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_internship',
            name='education',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('PhD', 'PhD')], default=None, max_length=200),
        ),
    ]
