# Generated by Django 6.0 on 2025-12-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VJISS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
