# Generated by Django 6.0 on 2025-12-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VJISS_APP', '0002_alter_apply_internship_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_internship',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
