# Generated by Django 6.0 on 2025-12-29 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VJISS_APP', '0002_rename_module_syllabus_model_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('specialization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialization_name', models.CharField(max_length=100)),
                ('specialization_description', models.TextField()),
                ('technologies', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='courses_model',
            old_name='public_id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='syllabus_model',
            old_name='public_id',
            new_name='syllabus_id',
        ),
    ]
