# Generated by Django 6.0 on 2025-12-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VJISS_APP', '0002_alter_create_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
