# Generated by Django 6.0 on 2025-12-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VJISS_APP', '0003_rename_full_name_apply_internship_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_internship',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
    ]
