# Generated by Django 6.0 on 2025-12-30 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VJISS_APP', '0005_alter_apply_internship_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Notifications',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('requirements', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='apply_internship',
            name='internship_offers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_offers', to='VJISS_APP.internshipoffers'),
        ),
    ]
