# Generated by Django 6.0 on 2026-01-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VJISS_APP', '0006_job_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=6),
        ),
    ]
